# data.csv(총합 파일) 결측치 제거

In [1]:
import pandas as pd
import numpy as np

In [2]:
flood_area_df=pd.read_csv('C:/SKN_24/ML_MINI_5TEAM/data/processed/flood_area.csv')
flood_dis_df=pd.read_csv('C:/SKN_24/ML_MINI_5TEAM/data/processed/Flooding_Disaster.csv')
riv_df=pd.read_csv('C:/SKN_24/ML_MINI_5TEAM/data/processed/riv_pro_df.csv')
solid_df=pd.read_csv('C:/SKN_24/ML_MINI_5TEAM/data/processed/solid_pump_data.csv')
waether_df=pd.read_csv('C:/SKN_24/ML_MINI_5TEAM/data/processed/weather_rain_data.csv')

In [3]:
flood_area_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17963 entries, 0 to 17962
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SIGUNGU      17963 non-null  int64
 1   FLOOD_YEAR   17963 non-null  int64
 2   FLOOD_MONTH  17963 non-null  int64
 3   FLOOD_AREA   17963 non-null  float64
dtypes: float64(1), int64(3)
memory usage: 561.5 KB

In [4]:
waether_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14960 entries, 0 to 14959
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SIGUNGU      14960 non-null  int64
 1   FLOOD_YEAR   14960 non-null  int64
 2   FLOOD_MONTH  14960 non-null  int64
 3   RAIN_TOTAL   14960 non-null  object
dtypes: int64(3), object(1)
memory usage: 467.6+ KB

In [5]:
merged_df=pd.merge(flood_area_df, waether_df, how='inner', on='SIGUNGU',)
merged_df

,SIGUNGU,FLOOD_YEAR_x,FLOOD_MONTH_x,FLOOD_AREA,FLOOD_YEAR_y,FLOOD_MONTH_y,RAIN_TOTAL
0,48170,2018,8,12218.564,2016,1,35.4
1,48170,2018,8,12218.564,2016,1,35.4
2,48170,2018,8,12218.564,2016,2,76.4
3,48170,2018,8,12218.564,2016,2,76.4
4,48170,2018,8,12218.564,2016,3,121.0
...,...,...,...,...,...,...,...
744048,46800,2021,7,41921.400,2025,7,274.6
744049,46800,2021,7,41921.400,2025,8,350.5
744050,46800,2021,7,41921.400,2025,9,148.0
744051,46800,2021,7,41921.400,2025,10,154.0
744052,46800,2021,7,41921.400,2025,11,27.2

In [6]:
merged_df.info()
#결측치 위치 확인 방법
merged_df.isnull()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 744053 entries, 0 to 744052
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   SIGUNGU        744053 non-null  int64
 1   FLOOD_YEAR_x   744053 non-null  int64
 2   FLOOD_MONTH_x  744053 non-null  int64
 3   FLOOD_AREA     744053 non-null  float64
 4   FLOOD_YEAR_y   744053 non-null  int64
 5   FLOOD_MONTH_y  744053 non-null  int64
 6   RAIN_TOTAL     744053 non-null  object
dtypes: float64(1), int64(5), object(1)
memory usage: 39.7+ MB

,SIGUNGU,FLOOD_YEAR_x,FLOOD_MONTH_x,FLOOD_AREA,FLOOD_YEAR_y,FLOOD_MONTH_y,RAIN_TOTAL
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
744048,False,False,False,False,False,False,False
744049,False,False,False,False,False,False,False
744050,False,False,False,False,False,False,False
744051,False,False,False,False,False,False,False
744052,False,False,False,False,False,False,False

In [7]:
# 결측치 몇 개인지 확인
merged_df.isnull().sum()

SIGUNGU          0
FLOOD_YEAR_x     0
FLOOD_MONTH_x    0
FLOOD_AREA       0
FLOOD_YEAR_y     0
FLOOD_MONTH_y    0
RAIN_TOTAL       0
dtype: int64

---

# merged_df=flood_area_df, waether_df
- solid_df riv_df
# merged_df1=merged_df,solid_df
-

In [9]:
merged_df1=pd.merge(merged_df,solid_df, how='inner',on="SIGUNGU")
merged_df1

,SIGUNGU,FLOOD_YEAR_x,FLOOD_MONTH_x,FLOOD_AREA,FLOOD_YEAR_y,FLOOD_MONTH_y,RAIN_TOTAL,DRAINAGE_GRD,PUMP_CNT
0,48170,2018,8,12218.564,2016,1,35.4,1,10
1,48170,2018,8,12218.564,2016,1,35.4,1,10
2,48170,2018,8,12218.564,2016,2,76.4,1,10
3,48170,2018,8,12218.564,2016,2,76.4,1,10
4,48170,2018,8,12218.564,2016,3,121.0,1,10
...,...,...,...,...,...,...,...,...,...
134882,47170,2021,8,1495.600,2025,9,146.3,1,6
134883,47170,2021,8,1495.600,2025,10,161.6,1,6
134884,47170,2021,8,1495.600,2025,10,161.6,1,6
134885,47170,2021,8,1495.600,2025,11,8.8,1,6
134886,47170,2021,8,1495.600,2025,11,8.8,1,6

In [10]:
merged_df2=pd.merge(merged_df1, riv_df, how='inner',on='SIGUNGU')
merged_df2

,SIGUNGU,FLOOD_YEAR_x,FLOOD_MONTH_x,FLOOD_AREA,FLOOD_YEAR_y,FLOOD_MONTH_y,RAIN_TOTAL,DRAINAGE_GRD,PUMP_CNT,RIV_GRD,RIV_DIS_MIN,RIV_DIS_GRD
0,48220,2016,10,44985.66,2016,1,70.7,1,4,3,206.280273,4
1,48220,2016,10,44985.66,2016,1,70.7,1,4,3,196.905242,4
2,48220,2016,10,44985.66,2016,1,70.7,1,4,2,826.648899,2
3,48220,2016,10,44985.66,2016,1,70.7,1,4,2,741.169158,2
4,48220,2016,10,44985.66,2016,1,70.7,1,4,2,556.730672,3
...,...,...,...,...,...,...,...,...,...,...,...,...
335372,47170,2021,8,1495.60,2025,9,146.3,1,6,3,420.505231,3
335373,47170,2021,8,1495.60,2025,10,161.6,1,6,3,420.505231,3
335374,47170,2021,8,1495.60,2025,10,161.6,1,6,3,420.505231,3
335375,47170,2021,8,1495.60,2025,11,8.8,1,6,3,420.505231,3
335376,47170,2021,8,1495.60,2025,11,8.8,1,6,3,420.505231,3

In [11]:
merged_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 335377 entries, 0 to 335376
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   SIGUNGU        335377 non-null  int64
 1   FLOOD_YEAR_x   335377 non-null  int64
 2   FLOOD_MONTH_x  335377 non-null  int64
 3   FLOOD_AREA     335377 non-null  float64
 4   FLOOD_YEAR_y   335377 non-null  int64
 5   FLOOD_MONTH_y  335377 non-null  int64
 6   RAIN_TOTAL     335377 non-null  object
 7   DRAINAGE_GRD   335377 non-null  int64
 8   PUMP_CNT       335377 non-null  int64
 9   RIV_GRD        335377 non-null  int64
 10  RIV_DIS_MIN    335377 non-null  float64
 11  RIV_DIS_GRD    335377 non-null  int64
dtypes: float64(2), int64(9), object(1)
memory usage: 30.7+ MB

In [12]:
merged_df2=merged_df2.rename(columns={'FLOOD_YEAR_x':'FLOOD_YEAR'})
merged_df2=merged_df2.rename(columns={'FLOOD_MONTH_x':'FLOOD_MONTH'})
merged_df2=merged_df2.rename(columns={'FLOOD_YEAR_y':'FLOOD_YEAR'})
merged_df2=merged_df2.rename(columns={'FLOOD_MONTH_y':'FLOOD_MONTH'})
merged_df2

,SIGUNGU,FLOOD_YEAR,FLOOD_MONTH,FLOOD_AREA,FLOOD_YEAR,FLOOD_MONTH,RAIN_TOTAL,DRAINAGE_GRD,PUMP_CNT,RIV_GRD,RIV_DIS_MIN,RIV_DIS_GRD
0,48220,2016,10,44985.66,2016,1,70.7,1,4,3,206.280273,4
1,48220,2016,10,44985.66,2016,1,70.7,1,4,3,196.905242,4
2,48220,2016,10,44985.66,2016,1,70.7,1,4,2,826.648899,2
3,48220,2016,10,44985.66,2016,1,70.7,1,4,2,741.169158,2
4,48220,2016,10,44985.66,2016,1,70.7,1,4,2,556.730672,3
...,...,...,...,...,...,...,...,...,...,...,...,...
335372,47170,2021,8,1495.60,2025,9,146.3,1,6,3,420.505231,3
335373,47170,2021,8,1495.60,2025,10,161.6,1,6,3,420.505231,3
335374,47170,2021,8,1495.60,2025,10,161.6,1,6,3,420.505231,3
335375,47170,2021,8,1495.60,2025,11,8.8,1,6,3,420.505231,3
335376,47170,2021,8,1495.60,2025,11,8.8,1,6,3,420.505231,3

In [15]:
total_data = merged_df2.copy()

#  CSV 저장
total_data.to_csv("C:/SKN_24/ML_MINI_5TEAM/data/processed/total_data.csv", index=False, encoding="utf-8-sig")
print(" 저장 완료: C:/SKN_24/ML_MINI_5TEAM/data/processed/total_data.csv")

 저장 완료: C:/SKN_24/ML_MINI_5TEAM/data/processed/total_data.csv