In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df_area = pd.read_csv("../../../data/processed/area.csv")
df_area.head()
# 이건 시각화 안 해도 될듯?

   SIDO SIDO_NAME  SIGUNGU SIGUNGU_NAME  AREA_NAME
0    11     서울특별시    11000           전체   서울특별시 전체
1    11     서울특별시    11110          종로구  서울특별시 종로구
2    11     서울특별시    11140           중구   서울특별시 중구
3    11     서울특별시    11170          용산구  서울특별시 용산구
4    11     서울특별시    11200          성동구  서울특별시 성동구

In [3]:
df_flood_area = pd.read_csv("../../../data/processed/flood_area.csv")
df_flood_area

       SIGUNGU  FLOOD_YEAR  FLOOD_MONTH  FLOOD_AREA
0        43111        2017            7   8420.8600
1        43111        2017            7   3860.0540
2        43111        2017            7   1686.6630
3        43111        2017            7  15485.9220
4        43111        2017            7  15076.9760
...        ...         ...          ...         ...
17958    46800        2021            7  41921.4000
17959    45730        2021            8    564.3333
17960    45730        2021            8   1132.0435
17961    44790        2022            8    708.8000
17962    44790        2022            8   1531.0000

[17963 rows x 4 columns]

In [4]:
df_flooding_disaster = pd.read_csv("../../../data/processed/Flooding_Disaster.csv")
df_flooding_disaster

      FLOOD_YEAR  DAM_RAIN  DEAD  SIGUNGU  FLOOD_GRD
0           2024     300.0   0.0    41480        2.0
1           2016     150.0   0.0    52770        2.0
2           2016     150.0   0.0    52770        2.0
3           2016     150.0   0.0    52770        2.0
4           2016     150.0   0.0    52770        2.0
...          ...       ...   ...      ...        ...
9254        2023     198.0   0.0    44760        2.0
9255        2018     198.0   0.0    46840        2.0
9256        2022     200.0   0.0    51730        2.0
9257        2023     198.0   0.0    52210        2.0
9258        2021       0.0   0.0    47770        2.0

[9259 rows x 5 columns]

In [5]:
df_riv = pd.read_csv("../../../data/processed/riv_pro_df.csv")
df_riv

      RIV_GRD  RIV_DIS_MIN  RIV_DIS_GRD  SIGUNGU
0           2   478.260258            3    51830
1           2   472.676208            3    51830
2           2   464.709738            3    51830
3           2   468.304507            3    51830
4           2   297.178959            4    51830
...       ...          ...          ...      ...
1462        2   229.527556            4    50110
1463        2   345.132782            3    50110
1464        2   452.014581            3    50110
1465        2   525.988454            3    50110
1466        3   467.574582            3    50110

[1467 rows x 4 columns]

In [6]:
df_weather = pd.read_csv("../../../data/processed/weather_rain_data.csv")
df_weather

       SIGUNGU  FLOOD_YEAR  FLOOD_MONTH RAIN_TOTAL
0        51820        2016            1        6.6
1        51780        2016            1        0.9
2        41250        2016            1        1.3
3        41480        2016            1        1.0
4        51760        2016            1        2.6
...        ...         ...          ...        ...
14955    48270        2025           11       18.3
14956    48860        2025           11       23.4
14957    48310        2025           11       31.0
14958    48840        2025           11       39.2
14959    26440        2025           11       27.0

[14960 rows x 4 columns]

In [7]:
pump_df = pd.read_csv("../../../data/processed/solid_pump_data.csv")
pump_df

    SIGUNGU  DRAINAGE_GRD  PUMP_CNT
0     51150             1         2
1     51170             1         1
2     41820             1         2
3     41281             2         5
4     41287             4         3
..      ...           ...       ...
77    44230             4         7
78    44200             2         5
79    44800             2         3
80    43800             1         1
81    43130             1         8

[82 rows x 3 columns]